import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'
import './theme.css'
import './cancel.css'
import './login-premium.css'
import './restaurant-tables.css'
import './dashboard-premium.css'
import './reports-premium.css'
import './settings-premium.css'
import './printer-dynamic.css'
import './print.css'

createRoot(document.getElementById('root')).render(<App />)
