import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'
import './theme.css'
import './cancel.css'
import './login-premium.css'
import './restaurant-tables.css'
import './dashboard-premium.css'
import './dashboard-compact.css'
import './reports-premium.css'
import './reports-complete-layout.css'
import './reports-header-actions-fix.css'
import './reports-simple-layout.css'
import './reports-print-scope-fix.css'
import './reports-print-scope-fix.js'
import './reports-calendar-runtime.js'
import './reports-actions-overlap-fix.css'
import './settings-premium.css'
import './tables-settings.css'
import './printer-dynamic.css'
import './print-settings-v2.css'
import './settings-tabs-fix.css'
import './summary-cards-compact.css'
import './settings-footer-actions-fix.css'
import './printer-table-compact-fix.css'
import './permissions-info-fix.css'
import './access-permissions-cleanup.css'
import './access-edit-runtime.js'
import './products-settings.css'
import './products-settings-runtime.js'
import './product-storage-sync.js'
import './print-settings-runtime.js'
import './print-runtime-compact-fix.js'
import './permissions-runtime.js'
import './tables-settings-cleanup.js'
import './mesas-auto-status.js'
import './mesas-waiter-hide-revenue.js'
import './waiter-command-permissions.js'
import './waiter-display-name-fix.js'
import './command-guests-editor.css'
import './kitchen-orders.css'
import './kitchen-orders-compact.css'
import './kitchen-waiter-print-fix.js'
import './kitchen-auto-refresh.js'
import './kitchen-print-guests-fix.js'
import './closing-cash.css'
import './closing-cash-refine.js'
import './closing-cash-bottom-fix.css'
import './closing-waiter-layout-fix.css'
import './closing-confirm-modal.js'
import './closing-print-scope-fix.css'
import './closing-print-scope-fix.js'
import './table-close-persist-fix.js'
import './print.css'
import './print-blank-fix.css'
import './thermal-print-runtime.js'
import './command-premium.css'
import './sidebar-logout-fix.css'
import './sidebar-logo-brand.css'
import './mobile-layout-fix.css'
import './waiter-kitchen-mobile-fix.css'
import './waiter-kitchen-final-mobile.css'
import './reports-final-actions-clean.css'
import './closing-other-details-readable.css'
import './waiter-persist-runtime-fix.js'

createRoot(document.getElementById('root')).render(<App />)

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/service-worker.js').catch(error => {
      console.warn('Service worker não registrado:', error.message)
    })
  })
}
