import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'
import './theme.css'
import './cancel.css'
import './login-premium.css'
import './restaurant-tables.css'
import './dashboard-premium.css'
import './dashboard-compact.css'
import './reports-premium.css'
import './settings-premium.css'
import './tables-settings.css'
import './printer-dynamic.css'
import './print-settings-v2.css'
import './settings-tabs-fix.css'
import './kitchen-orders.css'
import './kitchen-orders-compact.css'
import './print.css'
import './command-premium.css'

createRoot(document.getElementById('root')).render(<App />)
